"""create tasks table

Revision ID: a55fe31fde28
Revises: 5f02da3a2e06
Create Date: 2023-05-15 10:34:28.885348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a55fe31fde28"
down_revision = "5f02da3a2e06"
branch_labels = None
depends_on = None

task_status_enum_type = sa.Enum("open", "resolved", "overdue", name="task_status_enum")
task_visibility_enum_type = sa.Enum("visible", "archived", name="task_visibility_enum")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("deadline", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            task_status_enum_type,
            nullable=True,
        ),
        sa.Column(
            "visibility",
            task_visibility_enum_type,
            nullable=True,
        ),
        sa.Column("resolve_time", sa.DateTime(), nullable=True),
        sa.Column(
            "create_time",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_user_id"), "tasks", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_user_id"), table_name="tasks")
    op.drop_table("tasks")
    task_status_enum_type.drop(op.get_bind())
    task_visibility_enum_type.drop(op.get_bind())
    # ### end Alembic commands ###
