"""add indices on todo_items table

Revision ID: 9dd80e6dbed2
Revises: c64d586eeb63
Create Date: 2023-05-22 15:13:42.132924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9dd80e6dbed2"
down_revision = "c64d586eeb63"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_todo_items_deadline_when_opened",
        "todo_items",
        ["deadline"],
        unique=False,
        postgresql_where=sa.text("status = 'open' AND deadline IS NOT NULL"),
    )
    op.create_index(
        "ix_todo_items_deadline_when_visible_overdue",
        "todo_items",
        ["deadline"],
        unique=False,
        postgresql_where=sa.text(
            "visibility = 'visible' AND status = 'overdue' AND deadline IS NOT NULL"
        ),
    )
    op.create_index(
        "ix_todo_items_resolve_time_when_visible_resolved",
        "todo_items",
        ["resolve_time"],
        unique=False,
        postgresql_where=sa.text(
            "visibility = 'visible'"
            " AND status = 'resolved'"
            " AND resolve_time IS NOT NULL"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_todo_items_resolve_time_when_visible_resolved",
        table_name="todo_items",
        postgresql_where=sa.text(
            "visibility = 'visible'"
            " AND status = 'resolved'"
            " AND resolve_time IS NOT NULL"
        ),
    )
    op.drop_index(
        "ix_todo_items_deadline_when_visible_overdue",
        table_name="todo_items",
        postgresql_where=sa.text(
            "visibility = 'visible' AND status = 'overdue' AND deadline IS NOT NULL"
        ),
    )
    op.drop_index(
        "ix_todo_items_deadline_when_opened",
        table_name="todo_items",
        postgresql_where=sa.text("status = 'open' AND deadline IS NOT NULL"),
    )
    # ### end Alembic commands ###
