"""create todo_items table

Revision ID: c64d586eeb63
Revises: 5f02da3a2e06
Create Date: 2023-05-15 15:20:20.516831

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c64d586eeb63"
down_revision = "5f02da3a2e06"
branch_labels = None
depends_on = None

todo_item_status_enum_type = sa.Enum(
    "open", "resolved", "overdue", name="todo_item_status_enum"
)
todo_item_visibility_enum_type = sa.Enum(
    "visible", "archived", name="todo_item_visibility_enum"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "todo_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("deadline", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            todo_item_status_enum_type,
            server_default="open",
            nullable=False,
        ),
        sa.Column(
            "visibility",
            todo_item_visibility_enum_type,
            server_default="visible",
            nullable=False,
        ),
        sa.Column("resolve_time", sa.DateTime(), nullable=True),
        sa.Column(
            "create_time",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_todo_items_user_id"), "todo_items", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_todo_items_user_id"), table_name="todo_items")
    op.drop_table("todo_items")
    todo_item_status_enum_type.drop(op.get_bind())
    todo_item_visibility_enum_type.drop(op.get_bind())
    # ### end Alembic commands ###
