name: pull-request
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  lint-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Configure and start the application
        run: |
          cp .env.ci .env
          export DOCKER_USER_UID=$(id -u)
          export DOCKER_USER_GID=$(id -g)
          docker compose up --detach --build --wait api
      - name: Run code quality static analysis tools
        run: docker compose exec api ./do-lint.sh
      - name: Run tests
        run: docker compose exec api ./do-test.sh
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
